### ISSUE TITLE
PushNotificationIOS.addEventListener Doesn't Work

### ISSUE THREAD

**Issue by efecantekin** [react-native-community/push-notification-ios#102]
# Question
Hello,

I took a piece of code from example. Then I can get local notifications but eventListener doesn't work.

```
const onLocalNotification = (notification) => {
  Alert.alert(
    'Local Notification Received',
    `Alert message: ${notification.getMessage()}`,
    [
      {
        text    : 'Dismiss',
        onPress : undefined
      }
    ]
  );
};

const sendLocalNotification = () => {
  PushNotificationIOS.presentLocalNotification({
    alertBody   : 'BlaBla',
    alertTitle  : 'BlaBla',
    alertAction : 'undefined'
  });
};

componentDidMount() {
 PushNotificationIOS.addEventListener(
      'localNotification',
      onLocalNotification
    );
}

<Button
  onClick= sendLocalNotification
/>
```

When I click button, I can see notification. When I click it, alert doesn't work.

How can I solve this problem?

Thank you,

**Comment by lfabl** [comment]
I have the same problem.

**Comment by MorganTrudeau** [comment]
`UILocalNotification` is depreciated. The following method is no longer called.
`- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification;`

Instead we need to use the following method to receive tap action and change `didReceiveLocalNotification` method in RNCPushNotificationIOS.m to handle UNNotification.
`userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`

This message receives `UNNotificationResponse` which contains notification as `UNNotification`. More information here [IOS Docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc).

I can submit PR soon.

**Comment by lfabl** [comment]
Its work. Thanks. We wait for pr.

**Comment by MorganTrudeau** [comment]
PR submitted! 
https://github.com/react-native-community/push-notification-ios/pull/104

**Comment by lfabl** [comment]
Sorry. I have a one error.

`
2020-04-13 12:01:01.275732+0300 listempro[45328:1071903] -[UNNotification fireDate]: unrecognized selector sent to instance 0x600003b3fed0
2020-04-13 12:01:01.282258+0300 listempro[45328:1071903] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UNNotification fireDate]: unrecognized selector sent to instance 0x600003b3fed0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   listempro                           0x00000001051d3bae RCTFormatLocalNotification + 94
	6   listempro                           0x00000001051d3ade +[RNCPushNotificationIOS didReceiveLocalNotification:] + 94
	7   listempro                           0x0000000104e59c1a -[AppDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 170
	8   listempro                           0x00000001051b43f4 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 436
	9   UIKitCore                           0x00007fff47863dcb -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] + 6310
	10  UIKitCore                           0x00007fff46ddddb6 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 518
	11  UIKitCore                           0x00007fff46ddee4d -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	12  UIKitCore                           0x00007fff473b967e -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 504
	13  FrontBoardServices                  0x00007fff36555cc7 -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:] + 565
	14  FrontBoardServices                  0x00007fff3657ba5f __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2 + 123
	15  FrontBoardServices                  0x00007fff3655fd05 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	16  FrontBoardServices                  0x00007fff3657b99c __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke + 196
	17  libdispatch.dylib                   0x0000000105ed4d48 _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x0000000105ed7cb9 _dispatch_block_invoke_direct + 300
	19  FrontBoardServices                  0x00007fff365a143e __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	20  FrontBoardServices                  0x00007fff365a112c -[FBSSerialQueue _queue_performNextIfPossible] + 441
	21  FrontBoardServices                  0x00007fff365a163b -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	22  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	24  CoreFoundation                      0x00007fff23bb1924 __CFRunLoopDoSources0 + 180
	25  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	26  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	27  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	28  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	29  listempro                           0x0000000104e59e30 main + 112
	30  libdyld.dylib                       0x00007fff51a1dc25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
`

Does it have anything to do with this error?

**Comment by efecantekin** [comment]
> `UILocalNotification` is depreciated. The following method is no longer called.
> `- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification;`
> 
> Instead we need to use the following method to receive tap action and change `didReceiveLocalNotification` method in RNCPushNotificationIOS.m to handle UNNotification.
> `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`
> 
> This message receives `UNNotificationResponse` which contains notification as `UNNotification`. More information here [IOS Docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc).
> 
> I can submit PR soon.
> 
> ```
> // AppDelegate.m
> 
> // Called when notification is tapped
> - (void)userNotificationCenter:(UNUserNotificationCenter *)center
> didReceiveNotificationResponse:(UNNotificationResponse *)response
>          withCompletionHandler:(void (^)(void))completionHandler
> {
>   [RNCPushNotificationIOS didReceiveLocalNotification: response.notification];
> }
> ```
> 
> ```
> // RNCPushNotificationIOS.m
> 
> + (void)didReceiveLocalNotification:(UNNotification *)notification
>     API_AVAILABLE(ios(10.0))
> {
>   [[NSNotificationCenter defaultCenter] postNotificationName:kLocalNotificationReceived
>                                                       object:self
>                                                     userInfo:RCTFormatUNNotification(notification)];
> }
> ```

Thank you very much but it didn't work for me.
I copied didReceiveNotificationResponse method to AppDelegate.m, PushNotificationIOS.m and PushNotificationIOS.h from your PR. But the result is same with before. I can see notification but nut handle the click on it.()

**Comment by lfabl** [comment]
Its work!. Don't use the code on this page. Try the code sent as PR. Here is the link: https://github.com/react-native-community/push-notification-ios/pull/104/commits

**Comment by efecantekin** [comment]
> It works!. Try the code sent as PR. Here is the link: https://github.com/react-native-community/push-notification-ios/pull/104/commits Thanks @MorganTrudeau

Don't you understand what you read? The issue is about my problem and I couldn't solve it.
I wrote "didn't work **for me**".

I added didReceiveNotificationResponse to AppDelegate.m, PushNotificationIOS.m and PushNotificationIOS.h. Is there anything to do after adding this method? Re-run pod install, npm i etc?

**Comment by Kasheeram** [comment]
Try this if in your case app is launching on click of notification banner, This is only for iOS, Also check this as well: https://github.com/react-native-push-notification/ios

`useEffect(() => {
    PushNotificationIOS.getInitialNotification().then(payload => {
      console.log('ewrweioruwoeiruweodsfs', payload);
      if (payload) {
        navigateToSpecificScreen(
          payload._data.resource_id,
          payload._data.resource_type,
        );
      }
    });
  });`
