### ISSUE TITLE
Register event returns APNS token or FCM token?

### ISSUE THREAD

**Issue by Benzer1406** [react-native-community/push-notification-ios#108]
Hi,

I was just wondering if on iOS (physical device) the register event returns an APNS token by default or if the token could also be an FCM token in case Firebase is set up?

Thanks

**Comment by Benzer1406** [comment]
Just found out that on iOS it returns the APNS key. 
For those who use Firebase Cloud Messaging, keep in mind that you have to convert the APNS key to an FCM key.  Here's the documentation: https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens

**Comment by Mavenic** [comment]
Do we have to manually register tokens to FCM ?
