### ISSUE TITLE
Documentation became out-of-sync

### ISSUE THREAD

**Issue by SashaSirotkin** [react-native-community/push-notification-ios#110]
# Question

Hello maintainers!

PR #104 updated the documentation without an accompanying release. Anyone who tries to use the library will now receive a `No known class method for selector 'didReceiveNotificationResponse'` error.

Ideally there should be a `develop` branch to ensure that unreleased documentation changes are held back until the actual release.

**Comment by Naturalclar** [comment]
@SashaSirotkin Hello! Sorry about the documentation being out of date.
I've tested and released v1.2.0, so the docs should be in sync now.
From now on, I'll create a `next` branch and keep track of new changes there so there won't be any more confusions!

**Comment by willnaoosmit** [comment]
Hi! 
I'm using v1.2.0 with [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) and the error `No known class method for selector 'didReceiveNotificationResponse'` still persists :(

@SashaSirotkin did you found something?

**Comment by SashaSirotkin** [comment]
@willnaoosmit If you're upgrading, the `AppDelegate.m` got an extra line with the 1.2.0 release. I believe it this one:
```swift
// IOS 10+ Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  completionHandler();
}
```

**Comment by willnaoosmit** [comment]
@SashaSirotkin Thanks. It's fixed now!
