### ISSUE TITLE
Use of undeclared identifier 'RNCPushNotificationIOS'

### ISSUE THREAD

**Issue by binar1** [react-native-community/push-notification-ios#150]
### **Question**
-----------
the error will be shown  when i archive project  ,but on debug mode it works without any problem 

I imported 
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>

to AppDelegate.m
 also
 imported
 #import <UserNotifications/UNUserNotificationCenter.h>
and  i added UNUserNotificationCenterDelegate to protocols   in AppDelegete.h

<img width="752" alt="Screen Shot 2020-07-13 at 11 25 03 AM" src="https://user-images.githubusercontent.com/31405082/87282923-6fd19e80-c4fd-11ea-948e-d7be13b8e3ed.png">

**Comment by binar1** [comment]
i fixed the issue was i imported 
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
below  
#IF Debug
and this will available just when you are debug so it wont be found in archive

**Comment by betopompolo** [comment]
@binar1 thanks man! It works here

**Comment by pradyumnad** [comment]
@betopompolo @binar1 Do you mean 
`#IF Debug` for just the imports?

**Comment by betopompolo** [comment]
@pradyumnad no. As @binar1 pointed out, those imports:
```objc
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
```
should goes below the `#IF Debug` statement

**Comment by unicornRainbows** [comment]
Same here!! Ooopppsss..

**Comment by misaelcrespo30** [comment]
I have the problem when I try to package my application and I can not solve it, someone could help me with a solution
thank

**Comment by Anuj-logiciel** [comment]
Same problem here.

**Comment by tanoto-the-explorer** [comment]
I put it below if debug statement and I still got the error, what version are you guys using?

**Comment by binar1** [comment]
@tanoto-the-explorer don't put below if debug statement because it will be available just in debug mode , so you should don't put it below if debug

**Comment by akshay0542** [comment]
I have the same issue, I have move the import at the top as seen in attachment.
![image](https://user-images.githubusercontent.com/74226412/101635690-4f782280-3a50-11eb-86c4-9c9cd355bb3e.png)

**Comment by stguitar** [comment]
@akshay0542  this was EXACTLY my problem.  Thank you.

**Comment by KirillB-DevBrother** [comment]
@akshay0542 Thanks!

**Comment by MiloshN** [comment]
For me works this:

`#import "AppDelegate.h"

#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>`

Just under: `#import "AppDelegate.h"`

**Comment by prashant-wxit** [comment]
just add these two lines after #import "AppDelegate.h"

#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>

this works for me
