### ISSUE TITLE
How to differentiate whether a notification is being received or opened

### ISSUE THREAD

**Issue by TommyLeong** [react-native-community/push-notification-ios#177]
# Bug report

## Summary

I'm quite lost here with **how could we differentiate when a notification is RECEIVED? or OPENED?**. So we can perform a callback action depending on its state. 

In the [documentation of react-native-push-notification](https://github.com/zo0r/react-native-push-notification#usage), `onNotification` is triggered when a **remote notification** is received / opened or when **localNotification** is opened. This is not helpful to perform any action, since we don't know if the user has tapped on it.

With this setup, here's the behaviour:

**Android**
When App at Foreground **received** & **tapped** banner
- `onNotification` from `PushNotification.configure` is triggered 
- For whatever reason, `PushNotificationIOS.addEventListener('notification', ()=>{'remote notification is called!')});` get triggers as well.

When App at Background **received** banner
- nothing is processed, need to set a handler via the "setBackgroundMessageHandler" method. 

When App at Background **tapped** banner (pull down status to press)
- `onNotification` from `PushNotification.configure` is triggered 
- For whatever reason, `PushNotificationIOS.addEventListener('notification', ()=>{'remote notification is called!')});` get triggers as well.

**iOS** 
has 2 different behaviour, depending which one you setup with 

**iOS Case 1:**
With the suggestion given by [@mtettmar here ](https://github.com/react-native-community/push-notification-ios/issues/107#issuecomment-627365701)

When App at Foreground & Background **received**  banner
- nothing happened

When App at Foreground & Background  **tapped**  banner
- `onNotification` from `PushNotification.configure` is triggered 
- `PushNotificationIOS.addEventListener('localNotification', ()=>{console.log('localNotification is called')});`

**iOS Case 2:**
if you go with the following setup (you're going with this setup, most likely you are requesting device permission at a later stage, instead at the app launch state)
```
UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
```
When App at Foreground & Background **received**  banner
- nothing happened

When App at Foreground & Background  **tapped**  banner
- nothing happened

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 64.90 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.19.0
    react-native-cli: 2.0.1
```

Library version: 
`"@react-native-community/push-notification-ios": "^1.4.1",`
`"react-native-push-notification": "^5.0.1",`
`"@react-native-firebase/messaging": "^7.8.4",`

## Steps to reproduce

Currently the case scenario are tested with a few things implemented, 

`PushNotificationIOS.addEventListener('notification', ()=>{});`
`PushNotificationIOS.addEventListener('localNotification', ()=>{});`
`PushNotification.configure({...})`

Describe what you expected to happen:

**Case 1:**
1. App in Foreground
2. Notification appear
3. User tap on notification
4. App opens
4. JS does the callback processing

**Case 2:**
1. App in Foreground/Background
2. Notification appear
3. User missed the notification
4. User tap the notification later at notification center
5. App opens
6. JS does the callback processing

**Comment by DovletAmanov** [comment]
Could you fix it? I have same issue, can you please provide detailed information if you could fix it?

**Comment by TommyLeong** [comment]
@DovletAmanov  if you are using ios lib for this, check this link [here](https://github.com/react-native-push-notification-ios/push-notification-ios#how-to-determine-push-notification-user-click).

If you are using https://github.com/zo0r/react-native-push-notification , then you may check this link [here](https://github.com/zo0r/react-native-push-notification#handling-notifications)

Basically the userInteraction will return true when user tap at the notification banner that cause your app launhc
