### ISSUE TITLE
RCTPushNotificationManager does not set alertTitle in UILocalNotification

### ISSUE THREAD

**Issue by cpojer** [react-native-community/push-notification-ios#2]
* * *
  This issue was originally created by @stage88 as facebook/react-native#14699.
  * * *

  ### Description

Setting the alertTitle property on PushNotificationIOS.scheduleLocalNotification does not display the title in the notification.

With alertTitle set:
![image](https://user-images.githubusercontent.com/9906800/27482779-1ca92900-5866-11e7-8578-1afed9a5843d.png)

Without:
![image](https://user-images.githubusercontent.com/9906800/27482878-8083cc28-5866-11e7-8d69-6f4455fc4351.png)

### Reproduction Steps

Use the below code to reproduce.

#### Sample Code

`
PushNotificationIOS.scheduleLocalNotification({
      fireDate: new Date(Date.now() + (30 * 1000)).toISOString(),
      alertTitle: 'Incoming Message',
			alertBody: 'This is my message, please read it for good fortune.',
			soundName: 'default',
			applicationIconBadgeNumber: 1,
			userInfo: {
        id: 11
      }
    })
`

### Solution

Adding the following line in RCTPushNotificationManager.m (54) fixes the issue:

`notification.alertTitle = [RCTConvert NSString:details[@"alertTitle"]];`

### Additional Information

* React Native version: 0.45
* Platform: iOS
* Development Operating System: macOS Sierra 10.12.15
* Build tools: XCode 8.3.3

**Comment by Naturalclar** [comment]
alertTitle support has been added in `1.2.2` (#133) :tada: 

Thanks to @lukebars !

![Simulator Screen Shot - iPhone 11 - 2020-06-09 at 12 47 26](https://user-images.githubusercontent.com/6936373/84104149-e20f1900-aa4f-11ea-96a8-1fe2e02c155c.png)
