### ISSUE TITLE
Badge not updating in iOS 13.2.2

### ISSUE THREAD

**Issue by arnaudambro** [react-native-community/push-notification-ios#80]
# Bug
 In the componentDidMount of my App component, in the emulator iPhone 11 - iOS 13.2.2, I tried to `PushNotificationIOS.setApplicationIconBadgeNumber(50);` but nothing happens, whereas it sets the badge on the emulator iPhone 5s 10.3.1

**Comment by wildlifechorus** [comment]
I have the same issue, did you find any solution?

**Comment by arnaudambro** [comment]
nothing yet...

**Comment by arnaudambro** [comment]
Now it's working with iOS 13.5 and push-notifications-ios 1.2.0
