### ISSUE TITLE
has v1.1.0 BreakingChanges?

### ISSUE THREAD

**Issue by Psiiirus** [react-native-community/push-notification-ios#88]
# Question

Are there any BCs if i update from 1.0.7 from 1.1.0 ?
I've seen a lot of changes on iOS so I just wanted to ask.

**Comment by CrnogoracIvan** [comment]
Doesn't work. Cannot get token with  PushNotificationIOS.addEventListener.

**Comment by johuder33** [comment]
> Doesn't work. Cannot get token with PushNotificationIOS.addEventListener.

Same happen to me, but I use the library last Friday, and it retrieves the device token, but it doesn't respond to remote notification, any idea how to solve this ?

**Comment by johuder33** [comment]
I get the token device by executing the app in iOS 11, but for iOS 13 I can't get it, any idea why ?

**Comment by CrnogoracIvan** [comment]
> I get the token device by executing the app in iOS 11, but for iOS 13 I can't get it, any idea why ?

I rolled back to version 1.0.6 and it works on iOS 13. I did not tested it on older versions od iOS.

**Comment by Psiiirus** [comment]
@CrnogoracIvan is there any reason you ve rolled back to 1.0.6 instead of 1.0.7 ?

**Comment by CrnogoracIvan** [comment]
@Psiiirus I am not sure, but I think that on 1.0.7  PushNotificationIOS.addEventListener(register) is fired only once, when app is installed. I am sure that on 1.0.6 it works as expected.

**Comment by Psiiirus** [comment]
@CrnogoracIvan thanks i'm gonna check this!

**Comment by johuder33** [comment]
> > I get the token device by executing the app in iOS 11, but for iOS 13 I can't get it, any idea why ?
> 
> I rolled back to version 1.0.6 and it works on iOS 13. I did not tested it on older versions od iOS.

version ´1.0.6´ worwed for me 🎉 , FYI I testing on ´iOS 11.4´ and ´iOS 13.3.1´, that works great for me, for some reason when testing in ´iOS 13.3.1´ the register event gets slow, after some seconds it prints the device token, but works as expected.

**Comment by Psiiirus** [comment]
@johuder33 yeah i've noticed the same with the delayed onRegister triggering. well at least it is working ^^

**Comment by Psiiirus** [comment]
Hi @Naturalclar , just tried to upgrade to the 1.1.0 version with real device 13.1 and unf. it doesn't fire any register or registerError event...requestPermissions event works fine

**Comment by Naturalclar** [comment]
> Hi @Naturalclar , just tried to upgrade to the 1.1.0 version with real device 13.1 and unf. it doesn't fire any register or registerError event...requestPermissions event works fine

Sorry about that.. I'll look into it when I get the time
