### ISSUE TITLE
Foreground push notifications ios

### ISSUE THREAD

**Issue by Arjanvanmaren** [react-native-community/push-notification-ios#91]
I can't get foreground push notifications to work on ios. 

The willPresentNotification method does not get triggered by a firebase cloud messaging push notification.

Is there someone that managed to make this work?

**Comment by Arjanvanmaren** [comment]
I already fixed it, sorry.

**Comment by yayanartha** [comment]
How do you fixed that? Please explain @Arjanvanmaren

**Comment by simawn** [comment]
@Arjanvanmaren please tell us how you got it fixed!

**Comment by CarbonyDK** [comment]
Yeah, pls tell us!

**Comment by abhisekm** [comment]
If using firebase and local notification is not working, kindly check the link below

https://github.com/react-native-community/push-notification-ios/issues/63#issuecomment-617577579

**Comment by akshgods** [comment]
> I already fixed it, sorry.

let us know how you fix it

**Comment by Abhishek-Sankey** [comment]
Getting the same error, willPresentNotification method is not getting triggered.
